### ISSUE TITLE
Nuget ?

### ISSUE THREAD

**Issue by SympathyForTheDev** [chrisriesgo/android-swipelistview-sharp#3]
Hi ! another little question, can you publish the component in a Nuget ?

**Comment by chrisriesgo** [comment]
Great suggestion. Done! :)

[https://www.nuget.org/packages/FortySevenDeg.SwipeListView](https://www.nuget.org/packages/FortySevenDeg.SwipeListView)

**Comment by SympathyForTheDev** [comment]
Thanks !
